### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by stanislav-skrebtsov** [veusz/veusz#180] opened 2017-06-07 12:37 UTC
The problem happens when trying to open vsz file.
Probably it happens because this file was moved to another local disk in Windows (for example, from D: to H:).

**Traceback (most recent call last):**
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.loader", line 120, in executeScript
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.compat", line 167, in cexec
  File "<string>", line 1, in <module>
  File "G:/Temp/Veusz/20161229_03.vsz", line 5, in <module>
    ImportFileCSV(u'../Work/\u041d\u0430\u0443\u043a\u0430-\u042d\u043d\u0435\u0440\u0433\u043e\u0442\u0435\u0445/3. \u041f\u0440\u043e\u0435\u043a\u0442 \u042d\u043d\u0435\u0440\u0433\u043e\u0441\u0438\u0441\u0442\u0435\u043c\u044b \u043d\u0430 \u0431\u0430\u0437\u0435 \u0421\u041f\u0414\u0421/1. \u041e\u041a\u0420/\u042d\u0432\u043e\u0433\u0440\u0435\u0441\u0441 4.1/\u0410\u0440\u0445\u0438\u0432\u044b \u0434\u0430\u043d\u043d\u044b\u0445 \u0441 \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043e\u043a/PL-302/archive/2016/12/2016-12-26_003.csv', delimiter=';', linked=True, numericlocale=u'ru_RU')
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.dataimport.defn_csv", line 167, in ImportFileCSV
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.doc", line 171, in applyOperation
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.dataimport.base", line 273, in do
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.dataimport.defn_csv", line 79, in doImport
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.dataimport.readcsv", line 325, in readData
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.utils.utilfuncs", line 371, in get_unicode_csv_reader
IOError: [Errno 2] No such file or directory: u'../Work/\u041d\u0430\u0443\u043a\u0430-\u042d\u043d\u0435\u0440\u0433\u043e\u0442\u0435\u0445/3. \u041f\u0440\u043e\u0435\u043a\u0442 \u042d\u043d\u0435\u0440\u0433\u043e\u0441\u0438\u0441\u0442\u0435\u043c\u044b \u043d\u0430 \u0431\u0430\u0437\u0435 \u0421\u041f\u0414\u0421/1. \u041e\u041a\u0420/\u042d\u0432\u043e\u0433\u0440\u0435\u0441\u0441 4.1/\u0410\u0440\u0445\u0438\u0432\u044b \u0434\u0430\u043d\u043d\u044b\u0445 \u0441 \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043e\u043a/PL-302/archive/2016/12/2016-12-26_003.csv'

**Comment by jeremysanders** [comment] 2017-06-07 12:42
Probably, as Veusz tries to store relative filenames in documents, assuming that the data is stored with the document. If the document is moved but the data is not, then it will break. It's hard to know how to know what the correct behaviour should be.

**Comment by stanislav-skrebtsov** [comment] 2017-06-07 12:44
I suppose that in this case open dialog to show new path to csv file should be displayed.

**Comment by stanislav-skrebtsov** [comment] 2017-06-07 12:45
The same disk in Windows may have different names on different computers.

**Comment by jeremysanders** [comment] 2017-10-07 12:13
This should be fixed now.

**Closed by jeremysanders** 2017-10-07 12:13 UTC

**Comment by bohemyan** [comment] 2017-10-21 04:09
I have just downloaded the latest version today (2.0.1) and it appears the relative path does not work - at least for me.
At work, I imported data from CSV files , created a graph and saved in the same folder where the CSV files reside. Then I copied the entire folder on a portable drive to continue working on it at home. 
When I try to open the  vsz file I get an error  [errno22]Invalid argument //dor/files/mic/FtsZ... 

it seems to use absolute path to look for the data file. 
I was able to edit the veusz file and edit the path to just be the current ./DataFilename.csv  but since I carry files back and forth every day it is cumbersome. and I may need to do the same thing tomorrow when I bring the files to work. 
I think even if the data is linked there should be an option to pick whether relative or absolute path is used and/or have Veusz  look in the current folder and if it finds a file with the correct name ask whether it should use this file.      
 
Maybe there is some option that I am missing, for users who need to move the .vcz files often.

Thanks!
BTW, great program!


Stan 

Traceback (most recent call last):
  File "veusz\document\loader.py", line 120, in executeScript
  File "F:/Fig-2/fig2A-C.vsz", line 5, in <module>
    ImportFileCSV(u'//dor/Files/MIC/FtsZ_research/manuscripts/MinWoo-ms-2017/Fig-2/2C_FtsZ2-tARC6dJ-LS-graph.csv', linked=True, dsprefix=u'Z2-tARC6dJ-', rowsignore=1)
  File "veusz\dataimport\defn_csv.py", line 167, in ImportFileCSV
  File "veusz\document\doc.py", line 171, in applyOperation
  File "veusz\dataimport\base.py", line 273, in do
  File "veusz\dataimport\defn_csv.py", line 79, in doImport
  File "veusz\dataimport\readcsv.py", line 325, in readData
  File "veusz\utils\utilfuncs.py", line 366, in get_unicode_csv_reader
OSError: [Errno 22] Invalid argument: '//dor/Files/MIC/FtsZ_research/manuscripts/MinWoo-ms-2017/Fig-2/2C_FtsZ2-tARC6dJ-LS-graph.csv'

**Comment by jeremysanders** [comment] 2017-10-21 08:09
Please don't file new bugs under old closed ones.

Sorry, but I can't reproduce your problem. If you're putting slashes in filenames that might cause this issue, so don't do that.

**Comment by bohemyan** [comment] 2017-10-23 05:02
Hallo,

I think I know what is causing the problem. 

On computer 1 (at work) , where I created the Veusz plot with linked data (residing in the same folder as the Veusz plot), the files are on (mapped network) drive "Z"
this shows in the Veusz file:
# Veusz saved document (version 2.0.1)
# Saved at 2017-10-20T21:58:44.050447

AddImportPath('Z:\\MIC\\FtsZ_research\\manuscripts\\MinWoo-ms-2017\\Fig-2')
ImportFileCSV(u'//dor/Files/MIC/FtsZ_research/manuscripts/MinWoo-ms-2017/Fig-2/2C_FtsZ2-tARC6dJ-LS-graph.csv', linked=True, dsprefix=u'Z2-tARC6dJ-', rowsignore=1)
...
...
Please note that the "ImportFileCSV() function refers to an absolute path to the file, not just the file name
. 
I copied the folder with the Veusz plot and the linked .csv files to a USB drive and brought the files home, copied the folder to my home computer.
The home computer does not have the network mapped drive "Z" (so nothing is mounted in the root as //dor/Files/MIC/FtsZ_research/manuscripts/MinWoo-ms-2017/Fig-2/2C_FtsZ2-tARC6dJ-LS-graph.csv)  and hence when I try to open the Veusz plot, it cannot find the data file.

I have now learned not to link the data when importing, but it would be handy to be able to use a relative link (look in the same folder)  instead of the absolute path.  That seems to work in the current version except for when using mapped network drives


When I tried to replicate the error today on my home PC  I just copied a folder with the .csv data file and Veusz plot   into a different folder on the same PC. 
I could not get the error - the Veusz file opened fine even if I deleted the original folder.  I noticed that the Veusz file looked a little differently, because the ImportFileCSV()  referred to just a file name, not the full path:

# Veusz saved document (version 2.0.1)
# Saved at 2017-10-23T04:00:17.973123

AddImportPath('C:\\Users\\Family Account\\Documents\\Stan\\test-graph-1')
ImportFileCSV(u'1D-standards-S6.csv', headermode=u'1st', linked=True, dsprefix=u'Sephadex_6-', rowsignore=1)

 

So I think Veusz for some reasons uses absolute path when dealing with networked drive.

I hope my little report is helpful.

Best Regards,

Stan Vitha   







bohemian2012@aol.com

**Comment by jeremysanders** [comment] 2017-10-23 10:13
It works for me on a network drive. Are you sure you're not saving the document onto Z:\MIC... while importing the data from \\dor\Files\MIC...? Veusz can't see these are the same place (and use a relative path) unless you use one of Z:\ or \\dor\Files for the location of both the saved and imported files.

**Comment by bohemyan** [comment] 2017-10-23 14:29
Tested this morning with two scenarios:
 
I) A folder on the Z-drive, contains the .csv dataset, the Veusz file is saved into the same folder after importing data
\\dor\Files\MIC\FtsZ_research\manuscripts\test-folder 
 
Z:\MIC\FtsZ_research\manuscripts\test-folder>dir
 Volume in drive Z has no label.
 Volume Serial Number is F2F0-56C7
 Directory of Z:\MIC\FtsZ_research\manuscripts\test-folder
10/23/2017  08:49 AM    <DIR>          .
10/23/2017  08:49 AM    <DIR>          ..
10/20/2017  09:47 AM           604,652 Fig1D_data.csv
10/23/2017  08:55 AM               855 test-graph-1.vsz
               2 File(s)        605,507 bytes
               2 Dir(s)  355,944,374,272 bytes free

 
 
Veusz uses absolute path for the data file: 


# Veusz saved document (version 2.0.1)
# Saved at 2017-10-23T13:55:28.636968
　
AddImportPath('Z:\\MIC\\FtsZ_research\\manuscripts\\test-folder')
ImportFileCSV(u'//dor/Files/MIC/FtsZ_research/manuscripts/test-folder/Fig1D_data.csv', linked=True, dsprefix=u'test1-', rowsignore=1)




II) A folder created in C:\\Temp, contains the CSV dataset. The Veusz file is saved in the same folder after importing the dataset:
  
Directory of C:\Temp\testfolder_C_Temp
10/23/2017  08:58 AM    <DIR>          .
10/23/2017  08:58 AM    <DIR>          ..
10/20/2017  09:47 AM           604,652 Fig1D_data.csv
10/23/2017  09:00 AM               781 test-graph-C_Temp_folder.vsz
               2 File(s)        605,433 bytes
               2 Dir(s)  10,718,441,472 bytes free


In this case, Veusz does not use the full path for the data file, just the file name.



# Veusz saved document (version 2.0.1)
# Saved at 2017-10-23T14:00:11.737768
　
AddImportPath('C:\\Temp\\testfolder_C_Temp')
ImportFileCSV(u'Fig1D_data.csv', linked=True, dsprefix=u'test1-', rowsignore=1)
  


When I copy the folder (with both the .csv and .vsz files) from the Z: drive onto my C: drive  and unplug the network cable so that the network drive is no longer accessible, I get the error when I try to open the  Veusz file, since Veusz is trying to open the data file from the networked drive and not looking in the current folder.:

Traceback (most recent call last):
  File "veusz\document\loader.py", line 120, in executeScript
  File "C:\Temp\test-folder\test-graph-1.vsz", line 5, in <module>
    ImportFileCSV(u'//dor/Files/MIC/FtsZ_research/manuscripts/test-folder/Fig1D_data.csv', linked=True, dsprefix=u'test1-', rowsignore=1)
  File "veusz\dataimport\defn_csv.py", line 167, in ImportFileCSV
  File "veusz\document\doc.py", line 171, in applyOperation
  File "veusz\dataimport\base.py", line 273, in do
  File "veusz\dataimport\defn_csv.py", line 79, in doImport
  File "veusz\dataimport\readcsv.py", line 325, in readData
  File "veusz\utils\utilfuncs.py", line 366, in get_unicode_csv_reader
OSError: [Errno 22] Invalid argument: '//dor/Files/MIC/FtsZ_research/manuscripts/test-folder/Fig1D_data.csv'




Stan

bohemian2012@aol.com

 
 
-----Original Message-----

**Comment by jeremysanders** [comment] 2017-10-23 14:46
So there's no problem. Use the same drive / network share for both your data and vsz file. Veusz can't detect they are the same and I'm not sure what the correct behaviour would be then.
