### ISSUE TITLE
Cannot open files under directories with Korean characters in the path

### ISSUE THREAD

**Issue by junemo9** [veusz/veusz#221] opened 2017-12-01 08:19 UTC
As shown in the title, switching to version 2.0, veusz cannot open files under directories with Korean characters in the path. It was fine for the past versions.

**Comment by jeremysanders** [comment] 2017-12-01 08:40
Maybe this is the same as this: https://github.com/veusz/veusz/issues/216

Have you tried switching to 2.1.1? Is this on Windows?

It would be useful for someone with some Windows development expertise could take a look.

**Comment by junemo9** [comment] 2017-12-01 09:45
That is the problem for the version 2.1.1 on Windows. I wish this could be resolved.

**Comment by junemo9** [comment] 2017-12-01 09:47
I am using veusz on various environments. I'll check it on other OS.

**Comment by jeremysanders** [comment] 2017-12-01 09:47
Can you give some example names? I couldn't reproduce the issue with Chinese characters on English Windows, but maybe with the Korean ones it will be possible to debug.

Also, is it only when double clicking on the file, or do you have a problem with the File->Open dialog box?

**Comment by junemo9** [comment] 2017-12-01 09:59
I found that it works fine on Linux.

The following is the path for the directory containing the file in Windows machine.
G:\내 드라이브\Research\KFRI\03.고온살균우유\2017\microbial counts

It could not open files  either by double clicking or using the file open menu.

![capture](https://user-images.githubusercontent.com/34155140/33477627-aad3fa48-d6c9-11e7-9485-0ce97dcc778b.PNG)

The above is the screen capture of the error generated when opening a file.

**Comment by jeremysanders** [comment] 2017-12-01 10:01
Thanks - that error message is useful. I'll see whether I can work out why it is failing.

**Comment by junemo9** [comment] 2017-12-01 10:03
Thank you so much.

By the way, I should have said thank you for the developers like you for serving people with this great program, vuesz. 

Thank you.

**Comment by jeremysanders** [comment] 2017-12-01 10:06
Thanks!

I suspect this is caused by the error checking used to make sure files are not obviously harmful.
You could try starting the program as `veusz.exe --unsafe-mode` from the command line or run dialog and see whether you are able to open the saved file. Unsafe mode is not really unsafe if you only load your own documents.

**Comment by junemo9** [comment] 2017-12-01 10:17
Yes, I could open it by typing the command in the terminal by specifying the file I want to open.

**However, I could not open it using the file open menu after I launch the program by typing in the code, "vuesz --unsafe-mode".**

Anyway, I could open it by typing in the command at least.

Thank you.

**Comment by jeremysanders** [comment] 2017-12-03 10:59
I can't reproduce the problem, probably because I don't have a Korean Windows. I've made a guess at the possible problem. Can you try this version?

https://drive.google.com/open?id=197OlB8haJcImF1MblaSKVnL6cUSDc9DB

**Comment by junemo9** [comment] 2017-12-04 14:23
Sorry for the late reply.

It works beautifully and perfectly.

Thank you! Jeremy

**Comment by jeremysanders** [comment] 2017-12-09 09:52
This will be in the next proper release.

**Closed by jeremysanders** 2017-12-09 09:52 UTC
