### ISSUE TITLE
How to import the module scipy.interpolate into Veusz on Win10?

### ISSUE THREAD

**Issue by Qi0p** [veusz/veusz#642] opened 2022-12-29 10:17 UTC
I installed the Veusz on Win10 using the [Latest Windows binary (64 bit)](https://github.com/veusz/veusz/releases/download/veusz-3.4/veusz-3.4-x64-windows-setup.exe) ([GPG/PGP signature](https://github.com/veusz/veusz/releases/download/veusz-3.4/veusz-3.4-x64-windows-setup.exe.asc)), but I do not know how to import the python modules, e.g. scipy.interpolate? I tried Edit --> Custom definitions --> Imports --> Module: Scipy.interpolate & Symbol list: griddata. The console gives me red marks: Error evaluating...: name griddata is not defined.

I also tried install the python on my Win 10 system and set the python path from the preferences -> External.
 It still doesn't work.

Could someone have the same experience and help me solve this problem?

**Comment by korintje** [comment] 2023-01-14 15:58
The following issue will be helpful:
https://github.com/veusz/veusz/issues/480
As the last participant said, note that you should designate the path the modules exist, not Python exist.

I think it is better for us to improve the way to import external Python or Python modules.

**Comment by Dobrodzieju** [comment] 2023-01-17 21:14
Install miniconda and then conda install veusz. With conda you can install numpy, scipy, numba, whatevet you need.
I tried your way but it did not work for me also.

**Comment by jeremysanders** [comment] 2023-01-21 10:52
It should be possible to download an appropriate whl file from https://pypi.org/project/scipy/#files, unzip it (they are zip files) into a directory and add the surrounding directory to the path above. I've not tested this on windows, but it seems ok on linux.

The problem is (1) you need the version appropriate for the python version veusz was built with - type `sys.version` in the console to find that out, (2) it's possible that later versions of scipy will be incompatible with the numpy veusz was built with.

Maybe it's possible for someone to build a download dialog somewhere which could automate this. Adding scipy to veusz would increase the installer size by 100MB or so, I suspect.

**Closed** 2023-03-08 08:59 UTC

**Comment by mflamer** [comment] 2024-10-14 17:52
I also have some external Python scripts I'm using to preprocess data before importing it into Veusz. I need to automate this process for a colleague to use. The scripts use SciPy. I have carefully tried the steps listed here to import SciPy but can't get it to work. 

Is it possible to make this more automated? Could there be a way to "pip install" using the Python instance that Veusz is using? 

Thanks. I really appreciate any help. Veusz is a great application.
