### ISSUE TITLE
veusz 3.5.3 on apple/intel MacOS 12.6

### ISSUE THREAD

**Issue by gary14lex** [veusz/veusz#632] opened 2022-11-07 00:09 UTC
I have downloaded 3.5.3 three times and it fails to launch with the attached error on both intel and apple silicon. It is known that 14.0 of the apple command line tools are broken (in case you used that) but it might not affect Python. See[ this post](https://cloudyastrophysics.groups.io/g/Main/topic/macos_x_linker_problems_w/93861568?p=,,,20,0,0,0::recentpostdate/sticky,,,20,2,0,93861568,previd%3D9223372036854775807,nextid%3D1659096880899016127&previd=9223372036854775807&nextid=1659096880899016127) and those it references. They are fixed in 14.1.

screen shot attached.

thanks,
Gary
<img width="550" alt="Screen Shot 2022-11-06 at 6 59 08 PM" src="https://user-images.githubusercontent.com/7861950/200203103-91484d45-295b-45b3-9d87-c2c65e8d6029.png">

**Comment by korintje** [comment] 2022-11-07 07:19
Please see the following issue. A single line command works as a work around.
https://github.com/veusz/veusz/issues/630

I think it is better to keep the issue open.

**Comment by jeremysanders** [comment] 2023-02-21 08:34
Duplicate of #630

**Closed by jeremysanders** 2023-02-21 08:34 UTC
